# cloudbuild.yaml
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Run tests
  - name: 'node:18'
    entrypoint: npm
    args: ['test']
    env:
      - 'CI=true'
  # Upload test results to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'test-results.json', 'gs://startup2-56da7.firebasestorage.app/test-results-${BUILD_ID}.json']
    id: 'Upload Test Results'

  # Build the application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy to Firebase Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'dist/*', 'gs://startup2-56da7.firebasestorage.app/']
    id: 'Deploy to Firebase Storage'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY