# cloudbuild.yaml
steps:
# Fetch git history first
- name: 'gcr.io/cloud-builders/git'
  id: 'fetch-history'
  args: ['fetch', '--unshallow']

# Install dependencies
- name: 'node:18'
  id: 'install'
  entrypoint: npm
  args: ['install']

# Prepare tests
- name: 'node:18'
  id: 'prepare-tests'
  entrypoint: node
  args:
  - -e
  - |
    const { Storage } = require('@google-cloud/storage');
    const fs = require('fs');
    const { execSync } = require('child_process');
    
    // Get changed files with better error handling
    const getChangedFiles = () => {
      try {
        // First try to get files from current commit
        const output = execSync('git diff --name-only HEAD^ HEAD').toString();
        return output.split('\n').filter(file => file);
      } catch (error) {
        console.log('Failed to get changed files from git:', error.message);
        
        // Fallback: scan all test files
        try {
          console.log('Falling back to scanning all test files...');
          const output = execSync('find . -name "*.test.jsx" -o -name "*.test.js"').toString();
          return output.split('\n').filter(file => file);
        } catch (scanError) {
          console.log('Failed to scan for test files:', scanError.message);
          return [];
        }
      }
    };
    
    // Extract task ID from filename
    const getTaskId = (fileName) => {
      const match = fileName.match(/\.task(\d+)\.test\.jsx?$/);
      return match ? `task${match[1]}` : null;
    };
    
    // Group test files by task ID
    const groupTestsByTask = (files) => {
      const taskGroups = new Map();
      
      files.forEach(file => {
        // Remove './' from the beginning of file paths if present
        const cleanPath = file.replace(/^\.\//, '');
        const taskId = getTaskId(cleanPath);
        
        if (taskId) {
          if (!taskGroups.has(taskId)) {
            taskGroups.set(taskId, []);
          }
          taskGroups.get(taskId).push(cleanPath);
        }
      });
      
      return Object.fromEntries(taskGroups);
    };
    
    function createTestManifest() {
      console.log('Starting test manifest creation...');
      
      const changedFiles = getChangedFiles();
      console.log('Found files:', changedFiles);
      
      const taskGroups = groupTestsByTask(changedFiles);
      console.log('Grouped by tasks:', taskGroups);
      
      const manifest = {
        taskGroups,
        commit_id: process.env.COMMIT_SHA || 'unknown',
        repo_name: process.env.REPO_NAME || 'unknown',
        branch: process.env.BRANCH_NAME || 'unknown',
        timestamp: new Date().toISOString()
      };
      
      // Save manifest for next steps
      fs.writeFileSync('/workspace/test_manifest.json', JSON.stringify(manifest, null, 2));
      console.log('Test manifest created successfully');
    }
    
    createTestManifest();

# Run tests
- name: 'node:18'
  id: 'run-tests'
  entrypoint: node
  args:
  - -e
  - |
    const { Storage } = require('@google-cloud/storage');
    const fs = require('fs');
    const { spawn } = require('child_process');
    
    const storage = new Storage();
    const bucketName = '${_BUCKET_NAME}';
    const teamId = '${_TEAM_ID}';
    const projectId = '${_PROJECT_ID}';
    const uid = '${_UID}';
    
    class TaskTestRunner {
      constructor(taskId, testFiles) {
        this.taskId = taskId;
        this.testFiles = testFiles;
        this.results = {
          teamId,
          projectId,
          uid,
          taskId,
          timestamp: new Date().toISOString(),
          commit_id: process.env.COMMIT_SHA || 'unknown',
          branch: process.env.BRANCH_NAME || 'unknown',
          status: 'pending',
          testResults: []
        };
      }
      
      async addTestResult(testFile, result) {
        this.results.testResults.push({
          test_file: testFile,
          ...result,
          timestamp: new Date().toISOString()
        });
      }
      
      async saveToStorage() {
        this.results.status = 'completed';
        this.results.completed_at = new Date().toISOString();
        
        const fileName = `${teamId}.${projectId}.${uid}.${this.taskId}.json`;
        const bucket = storage.bucket(bucketName);
        const file = bucket.file(`test-results/${fileName}`);
        
        await file.save(JSON.stringify(this.results, null, 2), {
          contentType: 'application/json',
          metadata: {
            teamId,
            projectId,
            uid,
            taskId: this.taskId
          }
        });
        
        console.log(`Test results saved to: gs://${bucketName}/test-results/${fileName}`);
      }
      
      async runTests() {
        for (const testFile of this.testFiles) {
          try {
            console.log(`Running tests for: ${testFile}`);
            const result = await new Promise((resolve, reject) => {
              const jest = spawn('npm', ['test', testFile, '--json', '--silent']);
              let output = '';
              
              jest.stdout.on('data', (data) => {
                output += data;
              });
              
              jest.stderr.on('data', (data) => {
                console.error(`Test error: ${data}`);
              });
              
              jest.on('close', (code) => {
                try {
                  const results = JSON.parse(output);
                  resolve({
                    status: code === 0 ? 'passed' : 'failed',
                    testResults: results.testResults,
                    numPassedTests: results.numPassedTests,
                    numFailedTests: results.numFailedTests
                  });
                } catch (e) {
                  reject(e);
                }
              });
            });
            
            await this.addTestResult(testFile, result);
            
          } catch (error) {
            console.error(`Error running tests for ${testFile}:`, error);
            await this.addTestResult(testFile, {
              status: 'error',
              error: error.message
            });
          }
        }
        
        await this.saveToStorage();
      }
    }
    
    async function runAllTests() {
      console.log('Starting test execution...');
      
      const manifest = JSON.parse(fs.readFileSync('/workspace/test_manifest.json', 'utf8'));
      console.log('Loaded test manifest:', manifest);
      
      const taskPromises = Object.entries(manifest.taskGroups).map(([taskId, testFiles]) => {
        console.log(`Starting tests for task: ${taskId}`);
        const runner = new TaskTestRunner(taskId, testFiles);
        return runner.runTests();
      });
      
      await Promise.all(taskPromises);
      console.log('All tests completed');
    }
    
    runAllTests();

timeout: '1800s'
substitutions:
  _BUCKET_NAME: 'results'
  _TEAM_ID: 'auw8idk7'
  _PROJECT_ID: 'firebase-auth'
  _UID: 'o3uDfNNpaueWOBWxP11wLgL5Avg2'
options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY