# cloudbuild.yaml
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Run tests
  - name: 'node:18'
    entrypoint: npm
    args: ['test']
    env:
      - 'CI=true'

  # Build the application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy to Cloud Storage (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'dist/', 'gs://$_BUCKET_NAME']
    
  # Deploy to App Engine (optional)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['app', 'deploy']

timeout: '1800s'

substitutions:
  _BUCKET_NAME: 'your-bucket-name' # default value

options:
  logging: CLOUD_LOGGING_ONLY